---
- hosts: localhost
  name: Add Hosts and licenses to vCenter 
  gather_facts: false
  vars_files: ../answerfile.yml

  tasks:
    
    - name: Mount NFS datastores to ESXi - 02
      vmware_host_datastore:
          validate_certs: no
          hostname: '{{ vcenter_hostname }}.{{ domain }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          datastore_name: '{{ item.name }}'
          datastore_type: '{{ item.type }}'
          nfs_server: '{{ item.server }}'
          nfs_path: '{{ item.path }}'
          nfs_ro: no
          esxi_hostname: '{{ esxi_compute_01_fqdn }}'
          state: present
      delegate_to: localhost
      loop:
          - { 'name': 'Synology-NFS-Datastore', 'server': '192.168.10.201', 'path': '/volume1/NFS', 'type': 'nfs'}



    - name: Mount NFS datastores to ESXi - 03
      vmware_host_datastore:
          validate_certs: no
          hostname: '{{ vcenter_hostname }}.{{ domain }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          datastore_name: '{{ item.name }}'
          datastore_type: '{{ item.type }}'
          nfs_server: '{{ item.server }}'
          nfs_path: '{{ item.path }}'
          nfs_ro: no
          esxi_hostname: '{{ esxi_compute_02_fqdn }}'
          state: present
      delegate_to: localhost
      loop:
          - { 'name': 'Synology-NFS-Datastore', 'server': '192.168.10.201', 'path': '/volume1/NFS', 'type': 'nfs'}
