---
- hosts: localhost
  name: Deploy the VCSA to an ESXi Host
  gather_facts: false
  vars_files:
    vcsa_vars.yml
  tasks:
  - vmware_deploy_ovf:
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      name: '{{ vcenter_hostname }}'
      datastore: '{{ datastore }}'
      disk_provisioning: 'thin'
      networks: 
        "Network 1": "esxi_network"
      ovf: "{{ vcsa_ova_file }}"
      wait_for_ip_address: true
      validate_certs: no
      inject_ovf_env: true
      properties:
        DeploymentOption.value: "{{ vcsa_size }}" # VC t-shirt size: tiny,small,medium,large, or infrastructure
        guestinfo.cis.appliance.net.addr.family: 'ipv4' # ipv4 or ipv6
        guestinfo.cis.appliance.net.mode: 'static' # static or dhcp
        guestinfo.cis.appliance.net.addr: '{{ vcenter_address }}'
        guestinfo.cis.appliance.net.pnid: '{{ vcenter_hostname }}.{{ domain }}' # FQDN of vcenter server
        guestinfo.cis.appliance.net.prefix: '{{ net_prefix }}' #netmask CIDR notation, i.e. '24'
        guestinfo.cis.appliance.net.gateway: '{{ net_gateway }}'
        guestinfo.cis.appliance.net.dns.servers: '{{ dns_servers }}' # IP addresses of DNS servers.
        guestinfo.cis.appliance.root.passwd: '{{ vcenter_password }}'
        guestinfo.cis.ceip_enabled: "False"
        guestinfo.cis.deployment.autoconfig: 'True' # Auto-configure after deployment
        guestinfo.cis.vmdir.domain-name: '{{ domain }}'
        guestinfo.cis.vmdir.username: '{{ vcenter_username }}'
        guestinfo.cis.vmdir.password: '{{ vcenter_password }}' # SSO Password for administrator@vsphere.local
        guestinfo.cis.appliance.ntp.servers: 'us.pool.ntp.org'
        guestinfo.cis.appliance.ssh.enabled: 'True'
        domain: '{{ domain }}'
        searchpath: '{{ searchpath }}'
    delegate_to: localhost
  - name: wait for vCenter
    vmware_about_facts:
      hostname: '{{ vcenter_address}}'
      username: 'administrator@vsphere.local'
      password: '{{ vcenter_password }}'
      validate_certs: no
    delegate_to: localhost
    retries: 30
    delay: 60 
    register: result
    until: result is succeeded